name: .NET Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Build and Pack with dotnet
      run: dotnet pack --configuration Release

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: NuGet Package
        path: nupkg
